name: Deploy CRM a cPanel

on:
  push:
    branches:
      - main # Ejecuta el flujo de trabajo al detectar cambios en la rama main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest # Asigna un servidor virtual de Ubuntu para procesar las tareas
    steps:
    - name: Obtener código 
      uses: actions/checkout@v4 # Clona los archivos del repositorio dentro del servidor virtual

    - name: Preparar Node.js
      uses: actions/setup-node@v4 # Instala el entorno de Node.js en el servidor
      with:
        node-version: '18' # Establece la versión 18 de Node.js para compatibilidad con Angular 16

    - name: Instalar dependencias
      run: npm ci # Instala las dependencias de forma estricta basándose en el package-lock.json

    - name: Construir (Build)
      run: npm run build # Ejecuta el script "build" de tu package.json para compilar en modo producción

    - name: Subir a cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5 # Ejecuta la conexión y transferencia de archivos por FTP
      with:
        server: ${{ secrets.FTP_SERVER2 }} # Asigna la IP numérica desde los secretos de GitHub
        username: ${{ secrets.FTP_USERNAME2 }} # Asigna el usuario FTP desde los secretos
        password: ${{ secrets.FTP_PASSWORD2 }} # Asigna la contraseña FTP desde los secretos
        local-dir: ./dist/app/ # Establece la ruta de los archivos compilados que se van a subir
        server-dir: ./ # Establece la raíz de la cuenta FTP como destino final
        # Comentario agregado para forzar a GitHub a leer la nueva IP y descartar el error anterior